import {
  account,
  accountRelations,
  session,
  sessionRelations,
  user,
  userRelations,
  verification,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
} from "./auth.js";

export default {
  account,
  accountRelations,
  session,
  sessionRelations,
  user,
  userRelations,
  verification,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
};
